#!/bin/bash

pluglist=
if [[ $# == 0 ]]; then
    pluglist="$(grep '\*\*[^\*]*\*\*' from_github.md | sed 's/^....\([^:]*\)..:.*$/\1/')"
else
    pluglist="$@"
fi
for f in $pluglist
do
    clone="$(grep $f from_github.md | sed 's/.*`\(.*\)`.*$/\1/')"
    d=$(echo $clone | cut -f4 -d' ')
    if [[ ! -d "$d" ]]; then
        eval $clone
    fi
done



git config --global alias.st status
git config --global alias.co checkout
git config --global alias.ci commit
git config --global alias.br branch
git config --global alias.unstage reset HEAD
git config --global alias.last log -1
git config --global alias.lg log --color --graph --pretty format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
git config --global alias.cl clone
git config --global alias.di diff
